FROM ghcr.io/graalvm/graalvm-community:17 as builder

WORKDIR /app
COPY . /app

RUN gu install native-image

RUN ./gradlew nativeCompile

FROM scratch

COPY --from=builder /app/build/native/nativeCompile/versioning /versioning

ENTRYPOINT ["./versioning"]